name: Coot CI Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "aside-main" ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache coot dependencies
      id: cache-coot-dependencies
      uses: actions/cache@v3
      with:
         path: /home/runner/install/coot-Linux-ubuntu-gtk4
         key:  deps

    - name: Cache gemmi source
      id:   Cache-gemmi-source
      uses: actions/cache@v3
      with:
         path: gemmi
         key:  gemmi-cache-source

    - name: Cache gemmi build
      id:   Cache-gemmi-build
      uses: actions/cache@v3
      with:
         path: build-gemmi
         key:  gemmi-cache-build

    - name: Install system dependencies
      run: sudo apt-get install cmake libvorbis-dev libdw-dev libncurses5-dev libgtk-4-dev libasound2-dev
    - name: where are we?
      run:  pwd
    - name: build-with-build-it-3-3
      run:  bash build-it-3-3 || echo done
      # the install dir is set specifically in build-it-3-3 when we in github actions
    - name: run autogen.sh
      run:  bash autogen.sh
    - name: set-the-PATH
      run:  echo /home/runner/install/coot-Linux-ubuntu-gtk4/bin >> $GITHUB_PATH
    - name: run configure
      # we echo done so that this returns a success status so that the logs are always uploaded
      run: >
        ./configure --prefix=/home/runner/install/coot-Linux-ubuntu-gtk4
        --with-enhanced-ligand-tools
        --with-fftw-prefix=/home/runner/install/coot-Linux-ubuntu-gtk4
        --with-boost=/home/runner/install/coot-Linux-ubuntu-gtk4
        --with-gemmi=/home/runner/install/coot-Linux-ubuntu-gtk4
        --with-boost-libdir=/home/runner/install/coot-Linux-ubuntu-gtk4/lib
        --with-backward --with-libdw --with-sound --disable-static
        SHELL=/bin/bash
        PYTHON=/home/runner/install/coot-Linux-ubuntu-gtk4/bin/python3
        PKG_CONFIG_PATH=/home/runner/install/coot-Linux-ubuntu-gtk4/lib64/pkgconfig:/home/runner/install/coot-Linux-ubuntu-gtk4/lib/pkgconfig:/home/runner/install/coot-Linux-ubuntu-gtk4/lib/x86_64-linux-gnu/pkgconfig
        || echo done
    - name: compile make
      run:  make -j 4 || echo done
    - name: install make install
      run:  make install || echo done

    - name: upload config.log
      uses: actions/upload-artifact@v4
      with:
        name: upload-config-log-package
        path: ./config.log
        retention-days: 3

    - name: Upload build logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-public-html-package
        path: /home/runner/public_html
        retention-days: 3

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-binaries-package
        path: /home/runner/install
        retention-days: 3


