name: Coot CI macOS

on:
  push:

jobs:

  build-for-macos:

    runs-on: macos-latest

    steps:

    # I don't want to see Homebrew after coot has been installed
    # - name: Cache homebrew
    #   id:   cache-homebrew
    #   uses: actions/cache@v3
    #   with:
    #      path: /usr/local
    #      key: usr_local_homebrew

    - name: which brew?
      run:  which brew

    - name: Setup homebrew
      id:   setup-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: get coot.rb file
      # run:  wget https://raw.githubusercontent.com/YoshitakaMo/homebrew-bio/coot/Formula/coot.rb
      # try this modified version for now:
      run:  wget https://www2.mrc-lmb.cam.ac.uk/personal/pemsley/coot/files/coot.rb
      # don't stall waiting for user input to resolve the failed patch

    - name: compile homebrew coot HEAD
      run:  NONINTERACTIVE=1 brew install ./coot.rb --HEAD --verbose --debug --keep-tmp
