name: Coot CI Homebrew macOS

on:
  push:

jobs:

  build-for-macos:

    runs-on: macos-latest

    steps:

    # I don't want to a cache of Homebrew after coot has been installed
    # - name: Cache homebrew
    #   id:   cache-homebrew
    #   uses: actions/cache@v3
    #   with:
    #      path: /usr/local
    #      key: usr_local_homebrew

    - name: Which brew?
      run:  which brew

    - name: Setup homebrew
      id:   setup-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    # from https://support.circleci.com/hc/en-us/articles/360043542933--Error-The-brew-link-step-did-not-complete-successfully-When-Installing-Python
    # - name: brew unlink python@2
    #   run:  brew unlink python@2
    # -> didn't work: Error: No such keg: /usr/local/Cellar/python@2

    - name: Homebrew install python3
      run:  brew install python@3.12

    - name: Install Homebrew dependencies
      run:  >
         brew install boost boost-python3 brewsci/bio/clipper4coot
         brewsci/bio/raster3d brewsci/bio/ssm brewsci/bio/gemmi
         dwarfutils glib gmp gsl rdkit sqlite pygobject3

    - name: Get coot.rb file
      # run:  wget https://raw.githubusercontent.com/YoshitakaMo/homebrew-bio/coot/Formula/coot.rb
      # try this modified version for now:
      run:  wget https://www2.mrc-lmb.cam.ac.uk/personal/pemsley/coot/files/coot.rb
      # don't stall waiting for user input to resolve the failed patch

    - name: Compile Homebrew coot HEAD
      run:  NONINTERACTIVE=1 brew install ./coot.rb --HEAD --verbose --debug --keep-tmp

    - name: Does it run?
      run: coot --no-graphics < /dev/null

