name: libcootapi CI Ubuntu

on: 
  push:

jobs:

  build-libcootapi-for-ubuntu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache coot dependencies
        id: cache-coot-dependencies
        uses: actions/cache@v3
        with:
          path: /home/runner/install/coot-Linux-ubuntu-gtk4
          key:  coot-deps-ubuntu

      - name: Cache gemmi source
        id:   Cache-gemmi-source
        uses: actions/cache@v3
        with:
           path: gemmi
           key:  coot-build-ubuntu-gemmi-cache-source

      - name: Cache gemmi build
        id:   Cache-gemmi-build
        uses: actions/cache@v3
        with:
          path: build-gemmi
          key:  coot-build-ubuntu-gemmi-cache-build
        
      - name: Install system dependencies
        run: sudo apt-get install cmake libvorbis-dev libdw-dev libncurses5-dev libgtk-4-dev libasound2-dev
        #run: sudo apt-get install cmake libdw-dev libncurses5-dev 
    
      - name: Where are we?
        run:  pwd
    
      - name: Run build-with-build-it-3-3
        run:  bash build-it-3-3 || echo done
      
      - name: create-build-directory-for-libcootapi
        run: mkdir build-libcootapi

      - name: set the path
        run: echo /home/runner/install/coot-Linux-ubuntu-gtk4/bin >> $GITHUB_PATH

      - name: install nanobind
        run:  python3 -m pip install nanobind

      - name: run cmake
        run: > 
            cd build-libcootapi && 
            cmake -DCMAKE_INSTALL_PREFIX=/home/runner/install/coot-Linux-ubuntu-gtk4 
            -Dnanobind_DIR=/home/runner/install/coot-Linux-ubuntu-gtk4/lib/python3.11/site-packages/nanobind/cmake ..
        
      - name: make
        run: cd build-libcootapi && make -j 2
        
      - name: make install
        run: cd build-libcootapi && make install

    #   - name: test chapi
    #     run: python3 -m chapi

      - name: test 2 for chapi
        run: python3 python-tests/test_chapi2.py


        

